# Generated by Django 5.0.4 on 2024-05-03 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisense_no', models.CharField(max_length=200)),
                ('is_rent', models.BooleanField(default=False)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rent.city')),
                ('vehicles_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rent.vehicles_types')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField()),
                ('rent_time', models.DateTimeField()),
                ('expected_return_time', models.DateTimeField()),
                ('rent_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rent.city')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rent.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='vehicles_types',
            name='vender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_types', to='rent.vender'),
        ),
    ]
