# Generated by Django 5.0.4 on 2024-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_payment_type_violation_types_rent_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles_types',
            name='price_per_minute',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='vehicles_types',
            name='produce_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicles_types',
            name='size',
            field=models.IntegerField(choices=[(4, 'Small'), (7, 'Medium')], default=4),
        ),
    ]
